# fly.toml app configuration file generated for lobert-bot on 2025-05-05T18:06:18+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lobert-bot'
primary_region = 'sin'

[build]
  dockerfile = '.\Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
